### PR TITLE
Fix for babyman/quick-tabs-chrome-extension#363

### LINKED ISSUE #363: Quick-Tabs no longer works for "installed" pages
I noticed today that Quick-Tabs is no longer working with a website that has been "installed" as an app (via Settings, More Tools, Create Shortctut in the Brave browser). Specifically, the command Switch to Older Tab will get stuck on the page of the installed app and fail to move past it though I repeatedly press the shortcut.

I’m on Windows 10. Thanks for any help!

### PR DESCRIPTION
**Pull request by Wizek**
A quick and simple fix, I've been using it for about 2+ weeks now with great results. The issue is gone, and I did not notice any other issues (though while I do use quite a lot of app shortcuts, I have not tested it extensively with pop-out dev tools windows (which are handled specially by chrome), only a bit at the start where they seemed to work)

Fixes #363

### CODE REVIEW

**Comment by Wizek** [comment]
Works well under heavy use ever since then, no issues noted so far.

**Comment by rb-109** [comment]
@Wizek - Thank you so much for doing this. This bug has really reduced the usefulness of the extension for me, as I use the Google Chat web app, and the MRU just gets stuck on that and stops working. However, this does not seem to be in production yet. Is this correct?

@babyman Is this just awaiting your review? If so, please can you review and merge as this is the biggest flaw in what is otherwise a basically perfect extension

**Review by babyman — APPROVED** [review]

**Comment by babyman** [comment]
@rb-109 thanks for flagging this, I have merged the code but I already submitted the update for 2024.11.24 for review.  Seems that withdrawing that and resubmitting may slow down the review process :|.  I'll push this once the current update clears.

@Wizek, thanks for finding and fixing this bug, I tweaked the code a little after the merge but the behaviour should be the same.  Let me know if you have any concerns :)

**Comment by babyman** [comment]
Uploaded the update today for review, hopefully it should be live in a couple of days.

**Pull request merged**
