### PR TITLE
Improve switch behavior

### PR DESCRIPTION
**Pull request by MartinLichtblau**
**Fixes:**
certainly #229 
perhaps #232 since used function to focus windows was deprecated
certainly #245 
certainly #246 

**New:**
Various changes so that switching tabs behave as expected and usage becomes more intuitive.

### CODE REVIEW

**Comment by MartinLichtblau** [comment]
The prev/next wording seemingly confused programmers, since sometimes its the other way around.

**Comment by MartinLichtblau** [comment]
The options page still mentions that the old shortcuts are dead. Overall the options page would need some changes. This is why I didn't touch any of it. If that's ok. 
Also because the implementiont of #247 would change a lot.

**Comment by babyman** [comment]
Thanks for you hard work here, sorry it took me a couple of week to get it merged.

Evan

**Comment by MartinLichtblau** [comment]
Actually that's a good thing, since during this time it must proove its worth in practice :-D

**Pull request merged**
