### PR TITLE
Make it slightly more friendly-looking :)

### PR DESCRIPTION
**Pull request by theRealPadster**
Just some styling tweaks to make it a bit more friendly. 
screenshot from 2019-02-23 20-16-23

### CODE REVIEW

**Comment by babyman** [comment]
Thanks for taking the time to enhance the look of QuickTabs but I'm going to close this PR without merging it because appearance is sooooo subjective and because the changes can be handled tidily within the existing style options.

I have added your screenshot and css to the [themes directory](./3rdParty/css).

Thanks

**Comment by JoelAzaria** [comment]
@babyman heads-up the `themes directory` link above is 404.

**Comment by theRealPadster** [comment]
> @babyman heads-up the `themes directory` link above is 404.
Try [this](https://github.com/babyman/quick-tabs-chrome-extension/tree/master/3rdParty/css)

**Comment by JoelAzaria** [comment]
Thanks @theRealPadster, I found it by browsing the project tree.  Just informing that link was broken.

**Pull request closed without merging**
